dict_good_stuff_static = {
    "gojo satoru": "jujutsu kaisen",
    "nezuko kamado": "demon slayer kimetsu no yaiba",
    "zero two": "darling in the franxx",
    "tanjirou kamado": "demon slayer kimetsu no yaiba",
    "levi": "attack on titan",
    "killua zoldyck": "hunter x hunter",
    "sukuna": "jujutsu kaisen",
    "gawr gura": "hololive en",
    "zenitsu agatsuma": "demon slayer kimetsu no yaiba",
    "mai sakurajima": 'raseal does not dream of bunny girl senpal',
    "yuji itadori" :"jujutsu kaisen",
    "mikasa ackermann": "attack on titan",
    "hu tao": 'genshin impact',
    "manjiro sano": 'tokyo revengers',
    "shinobu kochou" : "demon slayer kimetsu no yaiba",
    "shouto todoroki": 'my hero academia',
    "eren jaeger": "attack on titan",
    "giyuu tomioka": "demon slayer kimetsu no yaiba",
    "rem": 'rezero starting life in another world',
    "megumi fushiguro": "jujutsu kaisen",
    "kyoujurou rengoku": "demon slayer kimetsu no yaiba",
    "naruto uzumaki": 'naruto',
    "ken kaneki": 'tokyo ghoul',
    "monkey d luffy": 'one piece',
    "eula": 'genshin impact',
    "mori calliope": 'hololive en',
    "itachi uchiha": 'naruto',
    "inosuke hashibira": "demon slayer kimetsu no yaiba",
    "rias gremory": "high school dxd",
    "hayase nagatoro": 'don\'t toy with me miss nagatoro',
    "toge inumaki": "jujutsu kaisen",
    "yumeko jabami": 'kakegurui',
    "katsuki bakugou" : 'my hero academia',
    "miku nakano": 'the quintessential quintuplets',
    "izuku midoriya": 'my hero academia',
    "zoro roronoa": "one piece",
    "akeno himejima": "high school dxd",
    "akaza": 'demon slayer kimetsu no yalba the moule mugen train',
    "nobara kugisaki": "jujutsu kaisen",
    "watson amelia": 'hololive en',
    "zhongli": 'genshin impact',
    "xiao": 'genshin impact',
    "asuna": 'sword art online',
    "gon freecss": 'hunter x hunter',
    "izumi miyamura": 'horimiya',
    "kakashi hatake": 'naruto',
    "megumin":'konosuba  god\'s bless on this wonderful world',
    "chika fujiwara": 'kaguyasama love is war',
    "jotaro kujo": '123456',
    "shouko komi":'komisan wa komyushou desu',
    "hisoka": 'hunter x hunter',
    "ai ooto":'wonder egg priority',
    "nino nakano": 'the quintessential quintuplets',
    "kaguya shinomiya": 'kaguyasama love is war',
    "violet evergarden": 'violet evergarden',
    "kento nanami" : "jujutsu kaisen",
    "osamu dazai": 'bungou stray dogs',
    "kyouko hori" : 'horimiya',
    "pieck finger": 'attack on titan the final season',
    "venti": 'genshin impact',
    "shoyo hinata": 'haikyuu',
    "sasuke uchiha": 'naruto',
    "ninomae ina\'nis": 'hololive en',
    "ninomae ina'nis": 'hololive en',
    "ninomae inanis": 'hololive en',
    "emilia":'rezero starting life in another world',
    "rimuru tempest":"that time i got relncarnated as a slime",
    "l": 'death note',
    "ganyu": 'genshin impact',
    "yanfei": 'genshin impact',
    "hange zoe": 'attack on titan',
    "2b": 'nier automata',
    "tobio kageyama": 'haikyuu',
    "himike toga": 'my hero academia 2',
    #Differrent Variation
    "himiko toga": 'my hero academia 2',
    "dio brando": '123456',
    "hanako": 'toiletbound hanakokun',
    "diluc": 'genshin impact',
    "asta":'black clover',
    "kenma kozume": 'haikyuu',
    "sniper mask":'highrise invasion',
    "sayu ogiwara":'123456',
    "kirito":'sword art online',
    "armin arlert": 'attack on titan',
    "mitsuri kanroji": "demon slayer kimetsu no yaiba",
    "paimon": 'genshin impact',
    "rin tohsaka":'fatestay night',
    "kurapika": 'hunter x hunter',
    "kanna kamui":'miss kobayashi\'s dragon maid',
    "goku": 'dragon bail z',
    "chizuru mizuhara":'kanojo okarishimasu',
    "esdeath":'akame ga kill',
    "childe": 'genshin impact',
    "shiro":'no game no life',
    "light yagami": 'death note',
    "fushi":'to your eternity',
    "roxy migurdia": 'mushoku tensei jobless reincarnation',
    "maki zenin" : "jujutsu kaisen",
    "takanashi kiara": 'hololive en',
    "saitama":'onepunch man',
    "langa hasegawa":'sk8 the infinity',
    "keqing": 'genshin impact',
    "akame":'akame ga kill',
    "takemichi hanagaki":'tokyo revengers',
    "kanao tsuyuri": "demon slayer kimetsu no yaiba",
    "dabi": 'my hero academia 2',
    "shouko nishimiya":'a silent voice',
    "kusuo saiki":'the disastrous life of saiki k',
    "saber":'fatestay night',
    "klee": 'genshin impact',
    "itsuki nakano": 'the quintessential quintuplets',
    "ram":'rezero starting life in another world',
    "karma akabane":'assassination classroom',
    "reki kyan":'sk8 the infinity',
    "nagito komaeda":'danganronpa 2 goodbye despair',
    "hinata hyuuga": 'naruto',
    #assassination classroom
    'nagisa shiota':'assassination classroom',
    'korosensei':'assassination classroom',
    #the disastrous life of saiki k
    'shun kaidou':'the disastrous life of saiki k',
    # 'pussy':'the disastrous life of saiki k',
    #a silent voice
    'shouya ishida':'a silent voice',
    # 'yuzuru nishimiya':'a silent voice',
    #tokyo revengers
    'hinata tachibana':'tokyo revengers',
    'atsushi sendo':'tokyo revengers',
    'naoto tachibana':'tokyo revengers',
    'ken ryuguji':'tokyo revengers',
    'chifuyu matsuno':'tokyo revengers',
    'atsushi sendo':'tokyo revengers',
    'naoto tachibana':'tokyo revengers',
    'takashi mitsuya':'tokyo revengers',
    'emma sano':'tokyo revengers',
    #sk8
    'miya chinen':'sk8 the infinity',
    'kojiro nanjo':'sk8 the infinity',
    'kaoru sakurayashiki':'sk8 the infinity',
    #no game
    'sora':'no game no life',
    'jibril':'no game no life',
    'schwi dola':'no game no life',
    #kanojo
    'sumi sakurasawa':'kanojo okarishimasu',
    'ruka sarashina':'kanojo okarishimasu',
    #k-on
    'mio akiyama':'kon',
    'yui hirasawa':'kon',
    'tsumugi kotobuki':'kon',
    # 'azusa nakano':'kon',
    # 'ritsu tainaka':'kon',
    #dragon ball
    'vegeta':'dragon ball z',
    'goku black':'dragon ball super',
    'gohan':'dragon ball z',
    'gogeta':'dragon ball 2 movie 12 fusion reborn',
    'future trunks':'dragon ball z',
    # 'vegito':'dragon ball z',
    # 'broly': 'dragon ball z moule 8 the legendary super salyan',
    #miss kob
    'tohru':'miss kobayashi\'s dragon maid',
    'lucoa':'miss kobayashi\'s dragon maid',
    # 'kobayashi':'miss kobayashi\'s dragon maid',
    #fate stay
    'astolfo':'fateapocrypha',
    'gilgamesh':'fatestay night',
    'ishtar':'fategrand order,',
    'archer':'fatestay night',
    #sword
    'sinon':'sword art online',
    'alice synthesis thirty':'sword art online alicization',
    # 'eugeo':'sword art online alicization',
    # 'yui':'sword art online',
    # 'yuuki':'sword art online',
    # 'leafa':'sword art online',
    #overflow
    'ayane shirakawa':"overflow",
    'kotone shirakawa':"overflow",
    #black clover
    'yami sukehiro':'black clover',
    'noelle silva':'black clover',
    'yuno':'black clover',
    'secre swallowtail':'black clover',
    'liebe':'black clover',
    'nacht faust':'black clover',
    # 'luck voltia':'black clover',
    # 'nero':'black clover',
    # 'tsuchigomori': 'toiletbound hanakokun',
    #nier
    'a2': 'nier automata',
    '9s': 'nier automata',
    #death
    'misa amane': 'death note',
    'ryuk': 'death note',
    #re;zero
    'echidna':'rezero starting life tn another world season 2',
    'subaru natsuki':'rezero starting life in another world',
    'ferris':'rezero starting life in another world',
    'beatrice':'rezero starting life in another world',
    #haikyuu
    'tooru oikawa':'haikyuu',
    'koutarou bokuto':'haikyuu second season',
    'yu nishinoya':'haikyuu',
    'tetsurou kuroo':'haikyuu',
    'kei tsukishima':'haikyuu',
    'koshi sugawara':'haikyuu',
    'keiji akaashi':'haikyuu second season',
    'satori tendou':'haikyuu second season',
    'atsumu miya':'haikyuu to the top',
    'rintarou suna':'haikyuu to the top',
    'tadashi yamaguchi':'haikyuu',
    'wakatoshi ushijima':'haikyuu',
    # 'ryunosuke tanaka':'haikyuu',
    # 'kiyoko shimizu':'haikyuu',
    # 'osamu miya':'haikyuu to the top',
    # 'kiyoomi sakusa':'haikyuu to the top',
    # 'hajime iwaizumi':'haikyuu',
    #attack on titan
    'sasha braus': 'attack on titan',
    'erwin smith': 'attack on titan',
    'annie leonhart': 'attack on titan',
    'jean kirschtein': 'attack on titan',
    'reiner braun': 'attack on titan',
    'yelena': 'attack on titan the final season',
    'christa lenz': 'attack on titan',
    'ymir': 'attack on titan',
    # 'zeke': 'attack on titan 2nd season',
    # 'falco grice': 'attack on titan the final season',
    # 'gabi braun': 'attack on titan the final season',
    # 'connie springer': 'attack on titan',
    # 'porco galliard': 'attack on titan the final season',
    #bungou
    'chuuya nakahara': 'bungou stray dogs',
    'ranpo edogawa': 'bungou stray dogs',
    'ryuunosuke akutagawa': 'bungou stray dogs',
    'atsushi nakajima': 'bungou stray dogs',
    # 'kyouka izumi': 'bungou stray dogs',
    #kaguya
    'ai hayasaka': 'kaguyasama love is war',
    'yu ishigami' : 'kaguyasama love is war',
    # 'miyuki shirogane': 'kaguyasama love is war',
    # 'kei shirogane': 'kaguyasama love is war',
    #tqq
    'yotsuba nakano': 'the quintessential quintuplets',
    'yotsuba nakanc':'the quintessential quintuplets',
    'ichika nakano': 'the quintessential quintuplets',
    'ichika nakan': 'the quintessential quintuplets',
    #demon
    "muichirou tokitou": "demon slayer kimetsu no yaiba",
    "obanai iguro": "demon slayer kimetsu no yaiba",
    "sabito": "demon slayer kimetsu no yaiba",
    "tengen uzui": "demon slayer kimetsu no yaiba",
    "sanemi shinazugawa": "demon slayer kimetsu no yaiba",
    "muzan kibutsuji": "demon slayer kimetsu no yaiba",
    "gyoumei himejima": "demon slayer kimetsu no yaiba",
    "enmu": "demon slayer kimetsu no yaiba",
    "iruma suzuki": "welcome to demon school frumakun",
    # "rui": "demon slayer kimetsu no yaiba",
    # "kanae kochou": "demon slayer kimetsu no yaiba",
    # "senjurou rengoku": "demon slayer kimetsu no yaiba",
    # "yoriichi tsugikuni": "demon slayer kimetsu no yaiba",
    # "makomo": "demon slayer kimetsu no yaiba",
    # "amelie azazel": "welcome to demon school frumakun",
    # "aurora suya rhys kaymin": "sleepy princess in the demon castle",
    # "tamayo": "demon slayer kimetsu no yaiba",
    #danganronpa
    "nagito komaeda":'danganronpa 2 goodbye despair',
    "chiaki nanami":'danganronpa 2 goodbye despair',
    "kokichi ouma":'danganronpa v3 killing harmony',
    "kyouko kirigiri":'danganronpa the animation',
    "junko enoshima":'danganronpa the animation',
    "ibuki mioda":'danganronpa 2 goodbye despair',
    "shuichi saihara":'danganronpa v3 killing harmony',
    "celestia ludenberg":'danganronpa the animation',
    "mikan tsumiki":'danganronpa 2 goodbye despair',
    "gundham tanaka":'danganronpa 2 goodbye despair',
    #hololive
    "irys": "hololive en",
    "inugami korone": 'hololive holo no graffiti',
    "usada pekora": 'hololive holo no graffiti',
    "shirakami fubuki": 'hololive holo no graffiti',
    "nekomata okayu": 'hololive holo no graffiti',
    "uruha rushia": 'hololive holo no graffiti',
    "moona hoshinova": 'hololive id',
    "kiryu coco": 'hololive holo no graffiti',
    "kureiji ollie": 'hololive id',
    "nakiri ayame": 'hololive holo no graffiti',
    "houshou marine": 'hololive holo no graffiti',
    "hoshimachi suisei": 'hololive holo no graffiti',
    "ayunda risu": 'hololive id',
    "minato aqua": 'hololive holo no graffiti',
    "shirogane noel": 'hololive holo no graffiti',
    # "shishiro botan": 'hololive holo no graffiti',
    # "tsunomaki watame": 'hololive holo no graffiti',
    #soul eater
    "death the kid": 'soul eater',
    "soul evans": 'soul eater',
    "crona": 'soul eater',
    "maka albarn": 'soul eater',
    # "franken stein": 'soul eater',
    # "black star": 'soul eater',
    #akame ga kill
    "mine": 'akame ga kill',
    # "chelsea": 'akame ga kill',
    # "leone": 'akame ga kill',
    #Dr. Stone
    # "gen asagiri": 'dr stone',
    #nekopara
    "vanilla":'nekopara',
    #wonder
    "rika kawai": 'wonder egg priority',
    "momoe sawaki": 'wonder egg priority',
    "neiru aonuma": 'wonder egg priority',
    #holostars
    "kanade izuru": 'holostars',
    # "kageyama shien": 'holostars',
    # "yukoku roberu": 'holostars',
    # "astel leda": 'holostars',
    #angel beats
    'kanade tachibana': 'angel beats',
    #bleach
    "ichigo kurosaki":'bleach',
    "kisuke urahara":'bleach',
    "rukia kuchiki":'bleach',
    "toshiro hitsugaya":'bleach',
    "grimmjow jeagerjaques":'bleach',
    # "yoruichi shihouin":'bleach',
    # "ulquiorra schiffer":'bleach',
    #persona 
    "joker":'persona 5 the animation',
    "ren amamiya":'persona 5 the animation',
    "futaba sakura":'persona 5 the animation',
    # "makoto niijima":'persona 5 the animation',
    # "goro akechi":'persona 5 the animation',
    # "ann takamaki":'persona 5 the animation',
    # "ryuji sakamoto":'persona 5 the animation',
    # "yu narukami":'persona 5 the animation',
    #that time i got reincarnated
    "milim nava":'that time  got retncamnated as a sttme',
    "shion":'that time  got retncamnated as a sttme',
    # "shuna":'that time  got retncamnated as a sttme',
    # "diablo":'that time  got retncamnated as a sttme',
    #one punch
    "genos":'onepunch man',
    'tatsumaki':'onepunch man',
    'garou':'onepunch man 2',
    'fubuki':'onepunch man',
    #High RIse
    "mayuko nise":"highrise invasion",
    "yuri honjou":"highrise invasion",
    #my hero academia
    "eijirou kirishima": 'my hero academia',
    "hawks": 'my hero academia 4',
    "denki kaminari": 'my hero academia',
    "shouta aizawa": 'my hero academia',
    "tamaki amajiki": 'my hero academia',
    'ochako uraraka': 'my hero academia',
    'tsuyu asui': 'my hero academia',
    'tomura shigaraki': 'my hero academia',
    'all might': 'my hero academia',
    'momo yaoyorozu': 'my hero academia',
    'kyouka jirou': 'my hero academia',
    'hitoshi shinsou': 'my hero academia 4',
    'eri': 'my hero academia 2',
    'fumikage tokoyami': 'my hero academia',
    'mina ashido': 'my hero academia',
    'mirko': 'my hero academia 4',
    'nejire hado': 'my hero academia 3',
    'mirio togata': 'my hero academia 3',
    # 'fat gum': 'my hero academia 4',
    # 'tenya iida': 'my hero academia',
    # 'overhaul': 'my hero academia 3',
    # 'hanta sero': 'my hero academia',
    #toilet
    "nene yashiro":'toiletbound hanakokun',
    "sousuke mitsuba":'toiletbound hanakokun',
    "tsukasa yugi":'toiletbound hanakokun',
    "kou minamoto":'toiletbound hanakokun',
    # "tsuchigomori":'toiletbound hanakokun',
    # "mokke":'toiletbound hanakokun',
    #jjk
    "yuta okkotsu" : "jujutsu kaisen",
    "aoi todo" : "jujutsu kaisen",
    "kasumi miwa": 'jujutsu kaisen',
    "choso": 'jujutsu kaisen',
    "sukuna's finger": 'jujutsu kaisen',
    "panda": 'jujutsu kaisen',
    "mahito": 'jujutsu kaisen',
    "suguru getou": 'jujutsu kaisen',
    "utahime iori": 'jujutsu kaisen',
    "mai zenin": 'jujutsu kaisen',
    "mei mei": 'jujutsu kaisen',
    # "junpei yoshino": 'jujutsu kaisen',
    #poke
    "james's amoonguss":'pokmon black  white adventures in unova',
    #angel beats
    "kanade tachibana": 'angel beats',
    #stein
    "kurisu makise":'steinsgate',
    "rintaro okabe":'steinsgate',
    # "mayuri shiina":'steinsgate',
    #teen romantic
    "yukino yukinoshita":'my teen romantic comedy snafu',
    "yui yuigahama":'my teen romantic comedy snafu',
    # "hachiman hikigaya":'my teen romantic comedy snafu',
    # "saika totsuka":'my teen romantic comedy snafu',
    #one piece
    "nico robin": "one piece",
    "nami": "one piece",
    "sanji": "one piece",
    "tony tony chopper": "one piece",
    "portgas d Ace": "one piece",
    "trafalgar law": "one piece",
    "usopp": "one piece",
    "shanks": "one piece",
    #shokugeki 
    "erina nakiri":'food wars shokugeki no souma',
    "souma yukihira":'food wars shokugeki no souma',
    "alice nakiri":'food wars shokugeki no souma',
    # "megumi tadokoro":'food wars shokugeki no souma',
    #mystic messenger
    "707":'mystic messenger',
    "jumin han":'mystic messenger',
    "zen":'mystic messenger',
    "unknown":'mystic messenger',
    "yoosung kim":'mystic messenger',
    # "jaehee kang":'mystic messenger',
    #black lagoon
    "revy":'black lagoon',
    #hunter
    "chrollo lucilfer": 'hunter x hunter',
    "feitan": 'hunter x hunter',
    "leorio paladiknight": 'hunter x hunter',
    # "killua's skateboard": 'hunter x hunter 2011',
    "illumi zoldyck": 'hunter x hunter',
    "meruem": 'hunter x hunter 2011',
    # "bungee gum": 'hunter x hunter 2011',
    "alluka zoldyck": 'hunter x hunter 2011',
    "pitou": 'hunter x hunter 2011',
    "shizuku": 'hunter x hunter',
    # "kite": 'hunter x hunter',
    # "scarlet eyes": 'hunter x hunter 2011',
    # "nanika": 'hunter x hunter 2011',
    #genshin
    "thoma": "genshin impact",
    "kamisato ayaka": "genshin impact",
    "kaeya": 'genshin impact',
    "razor": 'genshin impact',
    "fischl": 'genshin impact',
    "qiqi": 'genshin impact',
    "mona": 'genshin impact',
    "chongyun": 'genshin impact',
    "rosaria": 'genshin impact',
    "jean": 'genshin impact',
    "beidou": 'genshin impact',
    "scaramouche": 'genshin impact',
    "dainsleif": 'genshin impact',
    "bennett": 'genshin impact',
    "cyno": 'genshin impact',
    "lisa": 'genshin impact',
    "ningguang": 'genshin impact',
    "noelle": 'genshin impact',
    "amber" : 'genshin impact',
    "kaedehara kazuha": 'genshin impact',
    "aether": 'genshin impact',
    "xingqiu": 'genshin impact',
    "lumine": 'genshin impact',
    "sucrose": 'genshin impact',
    "diona": 'genshin impact',
    "barbara": 'genshin impact',
    "cyno": 'genshin impact',
    "taroumaru": 'genshin impact',
    "xiangling": 'genshin impact',
    "sayu": 'genshin impact',
    "baal": "genshin impact", "gorou": "genshin impact", "kujou sara": "genshin impact", "sangonomiya kokomi": "genshin impact", "yae miko": "genshin impact", "yoimiya": "genshin impact",
    #naruto
    "madara uchiha": 'naruto shippuden',
    "minato namikaze": 'naruto shippuden',
    "pain": 'naruto shippuden',
    "obito uchiha": 'naruto shippuden',
    "jiraiya": 'naruto',
    'gaara': 'naruto',
    'shikamaru nara': 'naruto',
    'sakura haruno': 'naruto',
    'rock lee': 'naruto',
    'tsunade': 'naruto',
    'shisui uchiha' : 'naruto shippuden',
    'neji hyuuga': 'naruto',
    'deidara': 'naruto shippuden',
    'boruto uzumaki': 'boruto naruto the movie',
    #jojo
    'giorno giovanna': '123456',
    'joseph joestar': '123456',
    'josuke higashikata': '123456',
    'josuke higashikato': '123456',
    'noriaki kakyoin': '123456',
    'yoshikage kira': '123456',
    # 'bruno bucciarati': '123456',
    # 'jonathan joestar': '123456',
    # 'robert e0 speedwagon': '123456',
    # 'kakyoin\'s cherry': '123456',
    # 'star platinum': '123456',
    # 'narancia ghirga': '123456',
    # 'jean pierre polnareff': '123456',
    # 'rohan kishibe': '123456',
    # 'guido mista': '123456',
    # 'caesar zeppeli': '123456',
    # 'okuyasu nijimura': '123456',
    # 'killer queen': '123456',
    # 'diavolo': '123456',
    #give
    'Mafuyu Sato':'given',
    'Ritsuka Uenoyama':'given',
    #Kill la Kill
    'ryuuko matoi': "kill la kill",
    # 'mako mankanshoku': "kill la kill",
    #citrus
    # 'mei aihara':'citrus',
    # 'yuzu aihara': 'citrus',
    #Kizumonogatari 
    'shinobu oshino': 'kizumonogatari movie 1 tehhetsu',
    'kissshot': 'kizumonogatari movie 1 tehhetsu',
    # 'tsubasa hanekawa': 'kizumonogatari movie 1 tehhetsu',
    # 'koyomi araragi': 'kizumonogatari movie 1 tehhetsu',
    #Konosuba
    'aqua':'konosuba  god\'s bless on this wonderful world',
    'darkness':'konosuba  god\'s bless on this wonderful world',
    'kazuma satou':'konosuba  god\'s bless on this wonderful world',
    # 'yunyun':'konosuba  god\'s bless on this wonderful world',
    # 'wiz':'konosuba  god\'s bless on this wonderful world',
    #Beyond the boundary
    'mirai kuriyama':'beyond the boundary',
    #Future Diary
    'yuno gasai': 'future diary',
    #Love Live
    # 'nico yazawa':'love live school idol project',
    # 'maki nishikino':'love live school idol project',
    #Fire Force
    'tamaki kotatsu' :'fire Force',
    'shinra kusakabe':'fire Force',
    'benimaru shinmon':'fire Force',
    # 'maki oze':'fire Force',
    # 'hibana':'fire Force',
    # 'arthur boyle':'fire Force',
    #to your eternity
    'march':'to your eternity',
    # 'parona':'to your eternity',
    # 'joaan':'to your eternity',
    #Tower Of God
    'khun aguero agnis':'tower of god',
    'twentyfifth baam':'tower of god',
    'yuri zahard':'tower of god',
    # 'androssi zahard':'tower of god',
    #The God of High School
    'jin mori':'the god of high school',
    # 'han daewi':'the god of high school',
    # 'park ilpyo':'the god of high school',
    #kimi ni todoke from me to you
    # 'sawako kuronuma': 'kimi ni todoke from me to you',
    # 'shota kazehaya': 'kimi ni todoke from me to you',
    #Spy X Family
    'yor forger':'spy x family',
    'anya forger':'spy x family',
    'loid forger':'spy x family',
    #Black Butler
    'sebastian michaelis':'black butler',
    'ciel phantomhive':'black butler',
    # 'grell sutcliff':'black butler',
    # 'undertaker':'black butler',
    #your name
    'mitsuha miyamizu':'your name',
    # 'taki tachibana':'your name',
    # Vivy: Fluorite Eye's Song
    'vivy':'vivy fluorite eye\'s song',
    #86 eightysix
    'vladilena Milize':'86 eightysix',
    # 'shinei nouzen':'86 eightysix',
    #higehiro after being rejected, i shaved and took in a high school runaway
    'airi gotou':'higehiro after being rejected, i shaved and took in a high school runaway',
    # 'yoshida':'higehiro after being rejected, i shaved and took in a high school runaway',
    #Charlotte
    'nao tomori':'charlotte',
    # 'yuu otosaka':'charlotte'
    #Noragami 
    'yato':'noragami',
    #The Way of the Househusband
    'tatsu':'the way of the househusband',
    'sakura yamauchi':'i want to eat your pancreas',
    #NEW
    'tsukasa yuzaki':'tonikaku kawaii',
    'raphtalia':'the rising of the shield hero',
    'naofumi iwatani':'the rising of the shield hero',
    'koneko toujou':'high school dxd',
    #kakegurui
    'mary saotome':'kakegurui',
    'runa yomozuki':'kakegurui',
    'midari ikishima':'kakegurui',
    'ririka momobami':'kakegurui',
    #horimiya
    'yuki yoshikawa':'horimiya',
    #fairy tail
    'natsu dragneel':'fairy tail',
    'erza scarlet':'fairy tail',
    'lucy heartfilia':'fairy tail',
    'gray fullbuster':'fairy tail',
    #bunny girl
    'rio futaba':'rascal does not dream of bunny girl senpai',
    'kaede azusagawa':'rascal does not dream of bunny girl senpai',
    'sakuta azusagawa':'rascal does not dream of bunny girl senpai',
    #the promised neverland
    'ray':'the promised neverland',
    'norman':'the promised neverland',
    #kaichou wa
    'takumi usui':'kaichou wa maidsama',
    'misaki ayuzawa':'kaichou wa maidsama',
    #seraph 
    'mikaela hyakuya':'seraph of the end: battle in nagoya',
    'shinoa hiiragi':'seraph of the end: battle in nagoya',
    'krul tepes':'seraph of the end:battle in nagoya',
    #record of ragnarok
    'adam':'record of ragnarok',
    'jack the ripper':'record of ragnarok',
    'brunhilde':'record of ragnarok',
    'aphrodite':'record of ragnarok',
    'kojiro sasaki':'record of ragnarok',
    #hyouka
    'eru chitanda':'hyouka',
    'houtarou oreki':'hyouka',
    #yuri on ice
    'victor nikiforov':'yuri on ice',
    #beastars
    'legosi':'beastars',
    #fruits basket
    'kyo sohma':'fruits basket',
    'tohru honda':'fruits basket',
    #nisekoi
    'chitoge kirisaki':'nisekoi',
    'kosaki onodera':'nisekoi',
    #banana fish
    'ash lynx':'banana fish',
    'eiji okumura':'banana fish',
    #fma
    'edward elric':'fullmetal alchemist',
    'roy mustang':'fullmetal alchemist',
    #mushoku
    'eris boreas greyrat':'mushoku tensei jobless reincarnation',
    'rudeus greyrat':'mushoku tensei jobless reincanation',
    'sylphiette':'mushoku tensei jobless reincarnation',
    #redo of healer
    'setsuna':'redo of healer',
    'flare arlgrande jioral':'redo of healer',
    'freia arlgrande jioral':'redo of healer',
    #weathering
    'hina amano':'weathering with you',
    #is it wrong
    'hestia':'is it wrong to try to pick up girls in a dungeon',
    #kuroko
    'tetsuya kuroko':'kuroko\'s basketball',
    'daiki aomine':'kuroko\'s basketball',
    #doki doki
    'monika':'doki doki literature club',
    'yuri':'doki doki literature club',
    'natsuki':'doki doki literature club',
    'sayori':'doki doki literature club',
    #classroom of the elite
    'kiyotaka ayanokouji':'classroom of the elite',
    'suzune horikita':'classroom of the elite',
    #date a live
    'kurumi tokisaki':'date a live',
    #killng slimes
    'azusa':'i\'ve been killing slimes for 300 years and maxed out my level',
    #overlord
    'albedo':'overlord',
    #Link Click
    'cheng xiaoshi': 'link click',
    'lu guang': 'link click',
    #solo Leveling
    "sung jinwoo": "solo leveling",
    "cha haein": "solo leveling",
    "igris": "solo leveling",
    "beru": "solo leveling",
    #Obey Me
    "mammon":"obey me",
    "lucifer":"obey me",
    "saki hanajima": 'fruit basket'
    # "atsuya baba": "oddtaxi", "ayumu gouriki": "oddtaxi", "dobu": "oddtaxi", "donraku shoufuutei": "oddtaxi", "eiji kakihana": "oddtaxi", "fuyuki yamamoto": "oddtaxi", "hajime tanaka": "oddtaxi", "haruhito yano": "oddtaxi", "hiroshi odokawa": "oddtaxi", "kenshirou daimon": "oddtaxi", "kensuke shibagaki": "oddtaxi", "koushirou daimon": "oddtaxi", "kurodadtaxi": "od", "miho shirakawa": "oddtaxi", "rui nikaidou": "oddtaxi", "sakura wadagaki": "oddtaxi", "shiho ichimura": "oddtaxi", "shun imai": "oddtaxi", "taeko harada": "oddtaxi", "taichi kabasawa": "oddtaxi", "togo sekiguchi": "oddtaxi", "yuki mitsuya": "oddtaxi",
    # "amira": "edens zero", "guiron": "edens zero", "hermit mio": "edens zero", "jaguar": "edens zero", "jamilov": "edens zero", "mller": "edens zero", "rebecca's bcube": "edens zero", "shinobi troll": "edens zero", "spider": "edens zero", "nagisa minase": "girlfriend girlfriend", "naoya mukai": "girlfriend girlfriend", "rika hoshizaki": "girlfriend girlfriend", "saki saki": "girlfriend girlfriend", "shino kiryuu": "girlfriend girlfriend", "aisha udgard": "how a realist hero rebuilt the kingdom", "albert elfrieden": "how a realist hero rebuilt the kingdom", "castor vargas": "how a realist hero rebuilt the kingdom", "elisha elfrieden": "how a realist hero rebuilt the kingdom", "excel walter": "how a realist hero rebuilt the kingdom", "georg carmine": "how a realist hero rebuilt the kingdom", "hakuya kwonmin": "how a realist hero rebuilt the kingdom", "jeanne euphoria": "how a realist hero rebuilt the kingdom", "juna doma": "how a realist hero rebuilt the kingdom", "kazuya souma": "how a realist hero rebuilt the kingdom", "kazuya's grandfather": "how a realist hero rebuilt the kingdom", "liscia elfrieden": "how a realist hero rebuilt the kingdom", "ludwin arcs": "how a realist hero rebuilt the kingdom", "marx": "how a realist hero rebuilt the kingdom", "poncho panacotta": "how a realist hero rebuilt the kingdom", "sebastian silvadia": "how a realist hero rebuilt the kingdom", "serina": "how a realist hero rebuilt the kingdom", "tomoe inui": "how a realist hero rebuilt the kingdom", "wodan udgard": "how a realist hero rebuilt the kingdom", "atena saotome": "mother of the goddess' dormitory", "frey": "mother of the goddess' dormitory", "fuki mamorukun": "mother of the goddess' dormitory", "kiriya senshou": "mother of the goddess' dormitory", "koushi nagumo": "mother of the goddess' dormitory", "mineru wachi": "mother of the goddess' dormitory", "serene hozumi": "mother of the goddess' dormitory", "sutea kouroya": "mother of the goddess' dormitory", "ai narata": "opera girl", "akiya shirakawa": "opera girl", "anai": "opera girl", "ayako yamada": "opera girl", "chiaki sawada": "opera girl", "chika sawada": "opera girl", "haruhiko oizumi": "opera girl", "hijiri nojima": "opera girl", "kaoru hoshino": "opera girl", "ken watanabe": "opera girl", "kimiko narata": "opera girl", "kirishima": "opera girl", "kitaouji mikiya": "opera girl", "kouzaburou shirakawa": "opera girl", "mamoru andou": "opera girl", "miki": "opera girl", "miki's mother": "opera girl", "nono": "opera girl", "onodera": "opera girl", "risa nakayama": "opera girl", "sarasa watanabe": "opera girl", "sawa sugimoto": "opera girl", "shun kuroge": "opera girl", "tachibana": "opera girl", "taichi narata": "opera girl", "tomomi takei": "opera girl", "asakaze": "sonny boy", "cap": "sonny boy", "hayato": "sonny boy", "hoshi": "sonny boy", "machi tanaka": "sonny boy", "mizuho koyama": "sonny boy", "nagara": "sonny boy", "nozomi": "sonny boy", "rajdhani": "sonny boy", "xiaomei": "edens zero", "aiko maebara": "when they cry higurashi", "rena's mother": "when they cry higurashi", "ritsuko": "when they cry higurashi", "rena's father": "when they cry kai"
} 

dict_good_stuff_addition = {
    
}

char_numbers = {
    # "xiaomei": 2, "aiko maebara": 2, "rena's mother": 2, "ritsuko": 2, "rena's father": 2
}